In [4]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5]) #1-d array
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8]]) #2-d array
print(arr)
print(arr.ndim) #printing no.of dimensions

[[1 2 3 4]
 [5 6 7 8]]
2


In [ ]:
arr = np.array([[[1,2,3,4],[5,6,7,8],[1,2,3,4]]]) #3-d array
print(arr)
print(arr.ndim)

[[[1 2 3 4]
  [5 6 7 8]
  [1 2 3 4]]]
3


In [ ]:
arr = np.array([1,2,3,4]) 
print(arr[3])

4


In [ ]:
arr = np.array([1,2,3,4]) 
print(arr[3]+arr[1])

6


In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8]]) #2-d array position of element
print(arr[0,1])

2


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) #3-d array position of element
print(arr[0,1,2])

6


In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8],[22,33,44,55]]) #Print the last element from the 2nd dim:
print(arr[1,-1])
print(arr)

8
[[ 1  2  3  4]
 [ 5  6  7  8]
 [22 33 44 55]]


In [10]:
# Flattening the arrays (Converting a multidimensional array into a 1D array)
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)
print(newarr.ndim)
print(newarr.shape)

[1 2 3 4 5 6]
1
(6,)


In [5]:
# Mean, Median and Standard deviation
a = np.arange(5,50,2)
print(a)
print('Mean :',np.mean(a))
print('Standard deviation :',np.std(a))
print('Median :',np.median(a))

# minimum along a column
print('Min :',np.min(a))
# maximum along a row
print('Max :',np.max(a))

[ 5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]
Mean : 27.0
Standard deviation : 13.2664991614216
Median : 27.0
Min : 5
Max : 49


In [6]:
# Array Arithmetic
a = np.array([[3, 2, 4], [5, 0, 1], [2, 5, 8]])
b = np.array([[1, 0, 5], [2, 3, 7], [6, 4, 5]])

print(a+2)
print(a-1)
print(a*5)
print(a/2)

c = a + b
print(c)

d = a - b
print(d)

e = a * b
print(e)

[[ 5  4  6]
 [ 7  2  3]
 [ 4  7 10]]
[[ 2  1  3]
 [ 4 -1  0]
 [ 1  4  7]]
[[15 10 20]
 [25  0  5]
 [10 25 40]]
[[1.5 1.  2. ]
 [2.5 0.  0.5]
 [1.  2.5 4. ]]
[[ 4  2  9]
 [ 7  3  8]
 [ 8  9 13]]
[[ 2  2 -1]
 [ 3 -3 -6]
 [-4  1  3]]
[[ 3  0 20]
 [10  0  7]
 [12 20 40]]


In [7]:
# NumPy Random
from numpy import random

x = random.randint(100)
print(x)

x1 = random.rand()
print(x1)

x2 = random.randint(100, size=(3, 5))
print(x2)

x3 = random.rand(3, 5)
print(x3)


82
0.46079319869293656
[[35 12 25 45 55]
 [82  6 30 47 17]
 [72 97  6 20 18]]
[[0.81010767 0.82119253 0.35852605 0.57937358 0.16551026]
 [0.8444953  0.59800698 0.81890653 0.99108394 0.89860612]
 [0.10701536 0.84076022 0.94278181 0.54085686 0.87980646]]


In [8]:
# Join two arrays

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [9]:
# Join two 2-D arrays along rows (axis=1)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [1]:
# Random Distribution
from numpy import random
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))
print(x)

y = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))
print(y)

[7 5 7 5 5 7 7 3 7 7 7 5 7 7 5 7 7 5 5 7 7 5 7 7 5 7 7 7 7 7 7 7 7 7 5 5 5
 7 5 5 3 5 5 3 5 5 5 3 5 7 7 5 7 7 5 7 5 5 7 5 7 5 3 7 7 7 7 7 3 7 3 7 7 7
 5 7 7 7 7 5 7 7 5 5 5 5 5 5 7 7 5 3 5 7 7 5 5 7 7 7]
[[5 5 7 5 5]
 [3 7 5 7 7]
 [7 5 3 7 7]]


In [2]:
x = random.normal(size=(2, 3))
print(x)

y = random.normal(loc=1, scale=2, size=(2, 3))
print(y)

[[ 1.03224247 -0.36850692  0.21793902]
 [ 0.78810504 -1.14418659  0.09003275]]
[[ 3.77557279  4.1277657  -0.42730869]
 [ 0.3731885   1.81272221  1.89601246]]
